create database customer_behavior;
use customer_behavior;
select * from customer c;

# 1. Total revenue generated by male & female
select c.gender, 
		SUM(c.purchase_amount) as total_revenue
from customer c 
group by c.gender;

# 2. Customers used discount still spent more than average purchase amount
select c.customer_id ,
		c.purchase_amount  
from customer c 
where c.discount_applied = 'Yes' and c.purchase_amount >= (select AVG(c.purchase_amount) from customer c);

# 3. Top 5 products with the highest average review rating
select c.item_purchased ,
		AVG(c.review_rating) as average_rating
from customer c
group by c.item_purchased  
order by average_rating desc 
limit 5;

# 4. Compare the average purchase amount b/w standard and express shipping
select c.shipping_type , 
		AVG(c.purchase_amount)
from customer c 
where c.shipping_type in ('Standard','Express')
group by c.shipping_type ;

# 5. Do subscribed customers spend more? Compare average spend and total revenue b/w subscribers & non subscribers
select c.subscription_status,
		COUNT(c.customer_id) as total_customer,
		AVG(c.purchase_amount) as average_spend,
		SUM(c.purchase_amount) as total_revenue
from customer c
group by c.subscription_status
order by total_revenue desc;

# 6. 5 products have highest no. of purchases with discount applied
select c.item_purchased,
		COUNT(c.item_purchased) as no_of_purchases,
		SUM(c.purchase_amount) as total_amt_of_purchases
from customer c 
where c.discount_applied = 'Yes'
group by c.item_purchased  
order by no_of_purchases desc
limit 5;

# 7. Segment customers into New, Returning & Loyal based on their total number of previous purchases and retrieve count of each segment
with customer_type as ( 
select c.customer_id, c.previous_purchases,
case
	when c.previous_purchases = 1 then 'New'
	when c.previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
end as customer_segment
from customer c
)
select customer_segment, 
		count(customer_segment) as no_of_customers
from customer_type
group by customer_segment;

# 8. Top 3 most purchased products within each category
with item_counts as(
select c.category,
		c.item_purchased ,
		COUNT(c.customer_id) as total_orders,
ROW_NUMBER() over(partition by c.category order by COUNT(c.customer_id ) desc ) as item_rank
from customer c 
group by c.category, c.item_purchased 
)
select item_rank, category, item_purchased, total_orders
from item_counts 
where item_rank <=3;

# 9. Customers who are repeated buyers (more than 5 previous purchase) also likely to subscribe
select c.subscription_status, 
		COUNT(c.customer_id) as repeated_customers
from customer c
where c.previous_purchases > 5
group by	 c.subscription_status;

# 10. Revenue contribution according to age groups 
select c.age_group,
		SUM(c.purchase_amount) as revenue_contribution
from customer c
group by c.age_group 
order by revenue_contribution desc; 

